"""add age column and check constraint

Revision ID: 9765a0a495bf
Revises: f35ef22b0fd0
Create Date: 2024-03-15 09:25:31.481828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9765a0a495bf'
down_revision = 'f35ef22b0fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.create_check_constraint('ck_age', 'age > 12')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('age')
        batch_op.drop_constraint('ck_age')

    # ### end Alembic commands ###
